name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: detekt
        run: ./gradlew detekt

      - name: Danger
        uses: danger/kotlin@1.0.0
        with:
          args: --dangerfile config/danger/config.df.kts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
